name: Build and Deploy on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t personal-qa-rag:${{ github.ref_name }} .

    - name: Save Docker image to tar
      run: docker save personal-qa-rag:${{ github.ref_name }} -o image.tar

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "image.tar"
        target: "~/"

    - name: SSH and run Docker container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker load -i image.tar
          docker stop personal-qa-rag || true
          docker rm personal-qa-rag || true
          docker run -d \
            --name personal-qa-rag \
            -p 80:8000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e SOURCE_URL=${{ secrets.SOURCE_URL }} \
            -e VERSION=${{ github.ref_name }} \
            personal-qa-rag:${{ github.ref_name }}
